### ISSUE TITLE
Question on making VM as weak as possible

### ISSUE THREAD

**Issue by 7MinSec** [NVISO-BE/SEC599#1]
Hi,

Just came upon your [Painless cuckoo install](https://blog.nviso.be/2018/04/12/painless-cuckoo-sandbox-installation/) article and am super pumped to give it a try.

I'm building out a Win VM and trying my best to keep it as weak as possible using this snippet as guidance:

>You will need to step out of your role as a blue team member to prepare this VM: this VM has to be as vulnerable as possible! To increase the chances of malware executing inside the VM, you will have to disable most of the protections and hardening you would implement on machines in your corporate network. For example, you will not install an anti-virus in this VM, disable UAC, don’t install patches,…

You also mention some recommendations about Office:

>To properly analyze malicious Office documents, you will use an older, unpatched version of Microsoft Office and you will disable macro security: you want the macros to run as soon as the document is opened, without user interaction.

Any recommendations on doing that?  I only see sites like [this one](https://www.microsoft.com/en-us/software-download/office) that let you submit an old Office key (which I don't have) to download an old Office version.  

Thanks,
Brian

**Comment by DidierStevens** [comment]
Hello Brian,

You need an official license or MSDN subscription to have access to older versions.

Cheers,

Didier

**Comment by 7MinSec** [comment]
OK thanks.  And just to be clear I wasn't promoting piracy :-).  I just hadn't looked for an old Office version in eons, so was wondering if I was missing the obvious.

Any other tips on making the VM as weak as possible besides:

* Disable UAC
* Old/unpatched Office version
* Disable Defender

?

Thanks,
Brian
