### ISSUE TITLE
Help figuring out why setup script bombs?

### ISSUE THREAD

**Issue by 7MinSec** [NVISO-BE/SEC599#2]
Hi,

I created a weak Windows VM, exported OVA over to Cuckoo box, tweaked the script to point to all the right paths (as far as I could tell) and here's the result:

<img width="328" alt="cuckoo" src="https://user-images.githubusercontent.com/17596787/39823050-c3962fcc-5371-11e8-80a5-6b21ac13f353.PNG">

Looking at your [blog entry](https://blog.nviso.be/2018/04/12/painless-cuckoo-sandbox-installation/) it seems like the text I'd want to see next is *Downloading Community Rules*.  Based on this image I can't really tell if the snapshot crapped out or if the problem was with downloading community rules.  Any ideas?

Thanks,
Brian

**Comment by DidierStevens** [comment]
Hi Brian,

I suggest you run the script again in verbose mode. We explain this in our blog post.

Cheers,

Didier

**Comment by 7MinSec** [comment]
Thanks - I ran

````
VBoxManage list vms
````
And found I had a name mismatch between that output and the cuckoo shell script.  Once the script was edited it was all green checks - yeah!

Thanks, anxious to give this a spin...

Brian
